#!/bin/bash

curl -X 'POST' \
  'http://localhost:5000/docker-compose' \
  -H 'accept: application/json' \
  -H 'Content-Type: text/plain' \
  -d 'HOST_HOSTNAME=website
HOST_IP=127.0.0.1
HOST_MAC=00:00:00:00:00:00
HOST_CPU=4
HOST_RAM=8GB
HOST_OS=Ubuntu
HOST_KERNEL=5.4.0
HOST_DOCKER=true
CACHE_HOST=cache
CACHE_PORT=6379
DATABASE_HOST=database
DATABASE_PORT=3306
DATABASE_NAME=coolcorp
DATABASE_USER=coolcorp
DATABASE_TABLE_PREFIX=wpapp_
WEBSITE_TITLE=CoolCorp
WEBSITE_DESCRIPTION="The best coders in town"
WEBSITE_HOSTNAME=coolcorp.xyz
WEBSITE_NAME=coolcorp
WEBSITE_ADMIN_FIRSTNAME=Abuzittin
WEBSITE_ADMIN_LASTNAME=Kodyazar
WEBSITE_ADMIN_USERNAME=cooladmin
WEBSITE_ADMIN_EMAIL=admin@coolcorp.xyz
MAIL_SMTP_HOST=smtp.coolcorp.xyz
MAIL_SMTP_PORT=587
MAIL_SMTP_USER=admin@coolcorp.xyz
MAIL_SMTP_PROTOCOL=tls
WORDPRESS_REDIS_HOST=cache
WORDPRESS_REDIS_PORT=6379
WORDPRESS_CACHE_ENABLED=true
WORDPRESS_CACHE_DURATION=1440
WORDPRESS_CACHE_TYPE=redis
PMA_USER=phpmyadmin_user
WOOCOMMERCE_ENABLED=true
WOOCOMMERCE_TAX_ENABLED=true
WOOCOMMERCE_TAX_COUNTRY=BE
WOOCOMMERCE_TAX_STATE=Vlaams-Brabant
WOOCOMMERCE_TAX_RATE=21
WOOCOMMERCE_TAX_SHIPPING_ENABLED=true
WOOCOMMERCE_TAX_SHIPPING_TAX_CLASS=standard
WOOCOMMERCE_TAX_SHIPPING_TAX_RATE=21
WOOCOMMERCE_TAX_SHIPPING_TAX_PRIORITY=1
WOOCOMMERCE_URL=https://coolcorp.xyz
WOOCOMMERCE_KEY=ck_cc98aff2b3e87a082f0bed39f42d5e618ae2e354
WOOCOMMERCE_SECRET=cs_bedb5887c9294e347eb3579ea18ce72fbbf6f633
WOOCOMMERCE_CURRENCY=EUR
WOOCOMMERCE_CURRENCY_POSITION=right
WOOCOMMERCE_CURRENCY_THOUSANDS_SEPARATOR=.
WOOCOMMERCE_CURRENCY_DECIMAL_SEPARATOR=,
WOOCOMMERCE_CURRENCY_DECIMALS=2
REMOTE_SERVER_USERNAME=root
REMOTE_SERVER_IP=coolcorp.xyz
REMOTE_SERVER_PORT=22
REMOTE_SERVER_PATH=/tmp
PROXY_TITLE=proxy
PROXY_HOSTNAME=proxy
' >> docker-compose.yml